Repository LT-Students/DigitalOffice-BrokerModels, pull requests merged in 2024-09, with the labels that each got.

#65 Add Id to FilePathData
  DigitalOffice.Models.nuspec
  src/Models/Broker/Models/File/FilePathData.cs
  src/Models/Models.csproj
Labels: enhancement

#66 Change ISendEmailWithFilesRequest and rename ISendEmailWithFilesRequest
  DigitalOffice.Models.nuspec
  src/Models/Broker/Requests/Email/ISendEmailWithAttachmentsRequest.cs
  src/Models/Models.csproj
Labels: enhancement

#68 Change ISendEmailAttachmentConsumer
  DigitalOffice.Models.nuspec
  src/Models/Broker/Requests/Email/ISendEmailWithAttachmentsRequest.cs
  src/Models/Models.csproj
Labels: enhancement

#69 Add ICheckContractSubjectExistenceRequest
  .gitignore
  DigitalOffice.Models.nuspec
  src/Models/Broker/Requests/Company/ICheckContractSubjectExistenceRequest.cs
  src/Models/Models.csproj
Labels: bug, enhancement

#70 Change ICheckContractSubjectsExistence
  DigitalOffice.Models.nuspec
  src/Models/Broker/Common/ICheckContractSubjectsExistence.cs
  src/Models/Broker/Requests/Company/ICheckContractSubjectExistenceRequest.cs
  src/Models/Models.csproj
Labels: bug
